version: '3.1'
services:
    web:
        #Use following image to download from Docker Hub
        #Image with giphypop
        image: jowings/docker-pets-giphy:latest
        deploy:
            mode: replicated
            replicas: 2
        ports:
         #   - 80
            - 7001:7000
        healthcheck:
            interval: 10s
            timeout: 2s
            retries: 3

        environment:
            DB: 'db'
            DEBUG: 'False'
            THREADED: 'True'
            ADMIN_PASSWORD_FILE: '/run/secrets/admin_password_v1'
            SERVICE_PORTS: '80'
            VIRTUAL_HOST: 'pets.2vcps.io'
        networks:
            - backend
            - lb-proxy
        secrets:
            - admin_password_v1

    db:
        image: consul:0.7.2
        command: agent -server -ui -client=0.0.0.0 -bootstrap-expect=3 -retry-join=db -retry-join=db -retry-join=db -retry-interval 5s
        deploy:
            replicas: 3
        ports:
            - 8500
        environment:
            CONSUL_BIND_INTERFACE: 'eth2'
            CONSUL_LOCAL_CONFIG: '{"skip_leave_on_interrupt": true}'
        networks:
            - backend

    viz:
        image: manomarks/visualizer
        #ports:
         #   - 8080:8080
        deploy:
            placement:
                constraints: [node.role == manager]
            labels:
                com.docker.ucp.mesh.http.8080: "external_route=http://<viz.url>,internal_port=8080"
        environment:
            SERVICE_PORTS: '8080'
            VIRTUAL_HOST: 'hello.2vcps.io'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - lb-proxy

networks:
    backend:
    lb-proxy:
        external: true

secrets:
    admin_password_v1:
        external: true
